### ISSUE TITLE
Generating knockoffs: map and IBD files?

### ISSUE THREAD

**Issue by biona001** [msesia/knockoffzoom-v2#2]
I simulated some genotypes and want to generate their knockoffs. I tried following the [tutorial](https://msesia.github.io/knockoffgwas/tutorial.html) and have a few questions, if I may?

1. Is the required map file the same as [PLINK's map file](https://zzz.bwh.harvard.edu/plink/data.shtml#map)? If so, why is the column names in the [example map files](https://github.com/msesia/knockoffgwas/blob/master/data/maps/genetic_map_chr21.txt) different than its specification? 
2. How do I generate these [IBD files](https://github.com/msesia/knockoffgwas/tree/master/data/ibd)?

Thanks in advanced.

**Comment by msesia** [comment]
1. No, the format of the required map file is not the same as that of PLINK's map file. The required format is that in the example map files. This is because, in addition to the chromosome number and BP position, you need estimated recombination rates (cM/BP) and the corresponding estimated genetic positions (cM) in order to generate knockoffs. See [here](https://www.ncbi.nlm.nih.gov/Class/MLACourse/Modules/Genomes/map_genetic.html) for more details on genetic maps. Genetic maps have been estimated for various human populations; you just need to find an appropriate one for your data, and cast it into the correct format for this software. 
2. The IBD files were obtained by post-processing the list of IBD segments identified by [RaPID](https://github.com/ZhiGroup/RaPID/blob/master/RaPID_v.1.7). RaPID doesn't give you output in exactly the correct format, but it does give you all relevant information (the chromosome number, the start and end BP positions of each IBD segment, as well as the individual and haplotype IDs for that segment). All you need to do is to transform the output of RaPID into this format. The last 5 columns (site.start site.end cM FAM1 FAM2) are not actually currently used. They need to be there (the file should have 12 fields in total), but it doesn't matter what values you put in them.
