### ISSUE TITLE
How many IBD segments is too many?

### ISSUE THREAD

**Issue by biona001** [msesia/knockoffzoom-v2#3]
Hello, 

I simulated 2k samples and 50k SNPs, for which `RaPID` returned around 6000 IBD segments.
On this data, `snpknock2` seems basically stuck at `Generating related knockoffs` (waited ~30 min and the progress bar did not move at all). After decreasing IBD segments to 20, the knockoffs were generated in ~20 min or so.

+ I wonder how many IBD segments is *too many*? According to RaPID paper, it seems millions of IBD segment is common for UKB data, so 6k shouldn't be that much? Should I have just waited longer?
+ Also, I wonder if multithreading (via the `n_threads` option) work beyond importing BGEN data?

**Comment by msesia** [comment]
The number of IBD segments isn't a bottleneck in itself, the problem may be that the "IBD-related families" (that's what they're called in the paper) are too large.
What I mean is that if you look at the relatedness graph for your haplotype sequences, where two nodes are connected if they share an IBD segment, it may be that the connected components are too large. The complexity of the algorithm depends on the size of the connected components.
If it makes sense with your data, try to make the connected components smaller. In the paper, we only considered IBD segments between individuals with self-reported relatedness, and excluding a handful of individuals, so that the largest IBD-sharing family wouldn't be too large.

The entire software is multi-threaded, not just reading the BGEN data.
________________________________
From: Benjamin Chu ***@***.***>
Sent: Wednesday, October 27, 2021 4:17 PM
To: msesia/knockoffgwas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [msesia/knockoffgwas] How many IBD segments is too many? (Issue #3)


Hello,

I simulated 2k samples and 50k SNPs, for which RaPID returned around 6000 IBD segments.
On this data, snpknock2 seems basically stuck at Generating related knockoffs (waited ~30 min and the progress bar did not move at all). After decreasing IBD segments to 20, the knockoffs were generated in ~20 min or so.

  *   I wonder how many IBD segments is too many? According to RaPID paper, it seems millions of IBD segment is common for UKB data, so 6k shouldn't be that much? Should I have just waited longer?
  *   Also, I wonder if multithreading (via the n_threads option) work beyond importing BGEN data?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fmsesia%2Fknockoffgwas%2Fissues%2F3__%3B!!LIr3w8kk_Xxm!5JfxMLtRKrC8SwkldIfaUPe0jAuZILCSL55rQO_PRZQB4HCGb6xD6k0vaw9TRCiw7lo%24&data=04%7C01%7Csesia%40marshall.usc.edu%7C3d68acd6002744f64f6508d9999fe47a%7Cc0ccb9c9d693495d84925136bb1940d6%7C0%7C0%7C637709734274372970%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JZYF9W1UUJ33XWW7qZ%2FC5iAQuPeOp%2Fd%2BYNaeS8%2FHSvk%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL63GUYHYOI7MZWAYBOA5WTUJCB7BANCNFSM5G3P4PEQ__%3B!!LIr3w8kk_Xxm!5JfxMLtRKrC8SwkldIfaUPe0jAuZILCSL55rQO_PRZQB4HCGb6xD6k0vaw9T_0JuNpw%24&data=04%7C01%7Csesia%40marshall.usc.edu%7C3d68acd6002744f64f6508d9999fe47a%7Cc0ccb9c9d693495d84925136bb1940d6%7C0%7C0%7C637709734274382966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K9lSsW1pHIWU04Zfsu6jUadjhMUkylrbA1rt4NYTzh8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675__%3B!!LIr3w8kk_Xxm!5JfxMLtRKrC8SwkldIfaUPe0jAuZILCSL55rQO_PRZQB4HCGb6xD6k0vaw9TTxGp92Q%24&data=04%7C01%7Csesia%40marshall.usc.edu%7C3d68acd6002744f64f6508d9999fe47a%7Cc0ccb9c9d693495d84925136bb1940d6%7C0%7C0%7C637709734274392958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dp%2F%2BCEWRh3wB5IGwvyeBRH1ooxYTUdRLTcLAtgqMcjs%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.com%2Fv3%2F__https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign*3Dnotification-email*26utm_medium*3Demail*26utm_source*3Dgithub__%3BJSUlJSU!!LIr3w8kk_Xxm!5JfxMLtRKrC8SwkldIfaUPe0jAuZILCSL55rQO_PRZQB4HCGb6xD6k0vaw9TM5k7k8I%24&data=04%7C01%7Csesia%40marshall.usc.edu%7C3d68acd6002744f64f6508d9999fe47a%7Cc0ccb9c9d693495d84925136bb1940d6%7C0%7C0%7C637709734274392958%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D%2B%2FvQHORCam6RA88x%2BXMD4CnLQiZ%2FwP0fIaxWEnux8s%3D&reserved=0>.

**Comment by biona001** [comment]
Thank you for the prompt response! That makes a lot of sense.
